const events = [
 {id:1,title:'AI & Machine Learning Workshop',category:'Workshop',date:'2026-07-28',time:'10:00 AM – 1:00 PM',venue:'Innovation Lab, Block B',organizer:'IEEE MBIT',count:83,description:'Build a practical understanding of machine learning workflows, from data preparation to model evaluation. Bring a laptop and leave with a small working project.'},
 {id:2,title:'Campus Hackathon 2026',category:'Hackathon',date:'2026-07-30',time:'9:00 AM – 9:00 PM',venue:'Central Auditorium',organizer:'CSI Student Chapter',count:147,description:'A one-day build sprint for teams with big ideas. Choose a campus or community problem, prototype a solution, and present it to a panel of mentors.'},
 {id:3,title:'Inter-College Basketball Tournament',category:'Sports',date:'2026-08-02',time:'4:00 PM – 7:00 PM',venue:'MBIT Sports Ground',organizer:'Sports Committee',count:62,description:'Cheer for MBIT as teams from across the region compete in an evening of fast-paced basketball. Open to all students and staff.'},
 {id:4,title:'Designing for the Web',category:'Technical',date:'2026-08-05',time:'11:00 AM – 12:30 PM',venue:'Seminar Hall 2',organizer:'Web Club MBIT',count:54,description:'Learn how thoughtful design systems make digital products clearer, more accessible, and easier to build. A hands-on session for new designers and developers.'},
 {id:5,title:'Cultural Night: Rang',category:'Cultural',date:'2026-08-09',time:'6:30 PM – 9:30 PM',venue:'Open Air Theatre',organizer:'Cultural Council',count:208,description:'An evening celebrating music, dance, and performances from across the MBIT community. Join us for student-led performances and campus celebration.'},
 {id:6,title:'Startup Stories & Strategy',category:'Seminar',date:'2026-08-12',time:'2:00 PM – 3:30 PM',venue:'Conference Room A',organizer:'E-Cell MBIT',count:39,description:'Founders and mentors share practical lessons on validating ideas, finding early customers, and building a team that can grow.'},
 {id:7,title:'CodeSprint Challenge',category:'Competition',date:'2026-08-16',time:'10:00 AM – 2:00 PM',venue:'Computer Lab 4',organizer:'Programming Club',count:71,description:'Test your problem-solving skills in a timed coding challenge with rounds for every experience level.'}
];
const categories=['All Events','Technical','Hackathon','Workshop','Cultural','Sports','Seminar','Competition'];
let selectedCategory='All Events', query='', interests=new Set(JSON.parse(localStorage.getItem('campus-interests')||'[]')), reminders=new Set(JSON.parse(localStorage.getItem('campus-reminders')||'[]')), calendarDate=new Date(2026,6,1), selectedDay=null;
const $=s=>document.querySelector(s), grid=$('#events-grid'), dialog=$('#event-dialog');
function fmtDate(date){return new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric'}).format(new Date(date+'T12:00:00'))}
function dayParts(date){const d=new Date(date+'T12:00:00');return {day:d.getDate(),month:new Intl.DateTimeFormat('en-IN',{month:'short'}).format(d)}}
function countdown(e){const d=(new Date(e.date+'T00:00:00')-new Date('2026-07-24T10:00:00'))/86400000;return d===0?'Happening today':`Starts in ${Math.ceil(d)} days`}
function visibleEvents(){return events.filter(e=>{const hay=`${e.title} ${e.category} ${e.organizer} ${e.venue}`.toLowerCase();return (selectedCategory==='All Events'||e.category===selectedCategory)&&(hay.includes(query.toLowerCase()))})}
function renderFilters(){ $('#filters').innerHTML=categories.map(c=>`<button type="button" class="filter" aria-pressed="${c===selectedCategory}" data-category="${c}">${c==='Hackathon'?'Hackathons':c==='Workshop'?'Workshops':c==='Seminar'?'Seminars':c==='Competition'?'Competitions':c}</button>`).join(''); }
function card(e){const saved=interests.has(e.id);return `<article class="event-card"><div class="event-meta"><span class="tag">${e.category}</span><span class="status">${countdown(e)}</span></div><h3><button type="button" data-open="${e.id}">${e.title}</button></h3><p>${e.description.slice(0,104)}…</p><div class="event-info"><span>◷ ${fmtDate(e.date)} · ${e.time}</span><span>⌖ ${e.venue}</span><span>by ${e.organizer}</span></div><div class="card-footer"><span class="people">${e.count + (saved?1:0)} interested</span><button class="interest-btn ${saved?'is-interested':''}" type="button" data-interest="${e.id}" aria-pressed="${saved}">${saved?'Interested ✓':'I’m interested'}</button></div></article>`}
function renderEvents(){const results=visibleEvents();grid.innerHTML=results.map(card).join('');$('#empty-state').hidden=results.length!==0;$('#result-note').textContent=query||selectedCategory!=='All Events'?`${results.length} event${results.length===1?'':'s'} found`:'';$('#upcoming-stat').textContent=String(events.length).padStart(2,'0');}
function persist(){localStorage.setItem('campus-interests',JSON.stringify([...interests]));localStorage.setItem('campus-reminders',JSON.stringify([...reminders]));}
let toastTimer;function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),2600)}
function toggleInterest(id){if(interests.has(id)){interests.delete(id);reminders.delete(id);toast('Removed from your interests.')}else{interests.add(id);toast('Saved to your interests.')}persist();renderAll();}
function renderInterests(){const saved=events.filter(e=>interests.has(e.id));$('#nav-interest-count').textContent=saved.length;$('#interest-stat').textContent=String(saved.length).padStart(2,'0');$('#interests-list').innerHTML=saved.length?saved.map(e=>{const d=dayParts(e.date), set=reminders.has(e.id);return `<div class="interest-item"><div class="interest-date"><strong>${d.day}</strong>${d.month}</div><div class="interest-main"><h3>${e.title}</h3><p>${e.time} · ${e.venue} · ${countdown(e)}</p></div><button class="reminder-btn" type="button" data-reminder="${e.id}" aria-pressed="${set}">${set?'Reminder on':'Set reminder'}</button></div>`}).join(''):`<div class="empty-interests"><strong>You haven’t saved any events yet.</strong>Explore upcoming events and mark the ones you want to attend.</div>`}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('#month-label').textContent=new Intl.DateTimeFormat('en-IN',{month:'long',year:'numeric'}).format(calendarDate);const first=new Date(y,m,1).getDay(), days=new Date(y,m+1,0).getDate(), dayEvents=events.reduce((a,e)=>{const d=new Date(e.date+'T12:00:00');if(d.getFullYear()===y&&d.getMonth()===m)(a[d.getDate()]??=[]).push(e);return a},{});let out='';for(let i=0;i<first;i++)out+='<button class="day" disabled aria-hidden="true"></button>';for(let d=1;d<=days;d++){const es=dayEvents[d]||[], sel=selectedDay===`${y}-${m}-${d}`;out+=`<button class="day ${es.length?'has-event':''} ${sel?'selected':''}" type="button" data-day="${d}" ${es.length?`aria-label="${d}, ${es.length} event${es.length>1?'s':''}"`:`aria-label="${d}, no events"`}>${d}</button>`}$('#calendar-grid').innerHTML=out}
function showDay(day){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();selectedDay=`${y}-${m}-${day}`;const es=events.filter(e=>{const d=new Date(e.date+'T12:00:00');return d.getFullYear()===y&&d.getMonth()===m&&d.getDate()===Number(day)});$('#date-events').innerHTML=es.length?`<strong>${fmtDate(es[0].date)}</strong><br>${es.map(e=>e.title).join(' · ')}`:'No events scheduled for this date.';renderCalendar()}
function openDetails(id){const e=events.find(x=>x.id===Number(id)),saved=interests.has(e.id),remind=reminders.has(e.id);$('#dialog-content').innerHTML=`<div class="dialog-inner"><span class="tag">${e.category}</span><h2 id="dialog-title">${e.title}</h2><p class="detail">${e.description}</p><div class="detail-grid"><div><strong>Date & time</strong>${fmtDate(e.date)}<br>${e.time}</div><div><strong>Location</strong>${e.venue}</div><div><strong>Organized by</strong>${e.organizer}</div><div><strong>Event status</strong>${countdown(e)} · ${e.count+(saved?1:0)} interested</div></div><div class="dialog-actions"><button class="reminder-btn" type="button" data-reminder="${e.id}" aria-pressed="${remind}" ${saved?'':'disabled'}>${remind?'Reminder on':'Set reminder'}</button><button class="interest-btn ${saved?'is-interested':''}" type="button" data-interest="${e.id}" aria-pressed="${saved}">${saved?'Interested ✓':'I’m interested'}</button></div></div>`;dialog.showModal()}
function renderAll(){renderFilters();renderEvents();renderInterests();renderCalendar()}
document.addEventListener('click',e=>{const f=e.target.closest('[data-category]');if(f){selectedCategory=f.dataset.category;renderAll()}const i=e.target.closest('[data-interest]');if(i){toggleInterest(Number(i.dataset.interest));if(dialog.open)openDetails(i.dataset.interest)}const r=e.target.closest('[data-reminder]');if(r){const id=Number(r.dataset.reminder);if(!interests.has(id))return;if(reminders.has(id)){reminders.delete(id);toast('Reminder turned off.')}else{reminders.add(id);toast('Reminder is on for this event.')}persist();renderInterests();if(dialog.open)openDetails(id)}const o=e.target.closest('[data-open]');if(o)openDetails(o.dataset.open);const d=e.target.closest('[data-day]');if(d)showDay(d.dataset.day);if(e.target.closest('.dialog-close'))dialog.close();if(e.target.closest('.menu-toggle')){$('.primary-nav').classList.toggle('open');const expanded=$('.primary-nav').classList.contains('open');$('.menu-toggle').setAttribute('aria-expanded',expanded)}});
$('#search-input').addEventListener('input',e=>{query=e.target.value;renderEvents()});$('#prev-month').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);selectedDay=null;renderCalendar()};$('#next-month').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);selectedDay=null;renderCalendar()};dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});renderAll();
